# Generated by Django 2.0.8 on 2018-09-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydropower',
            name='issue1_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hydropower',
            name='validity1_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
