# Generated by Django 2.0.8 on 2018-08-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydropower',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hydropower',
            name='longitude',
        ),
    ]
