# Generated by Django 2.0.8 on 2018-08-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydropower',
            name='license_type',
            field=models.IntegerField(default=0),
        ),
    ]
