# Generated by Django 2.0.8 on 2018-08-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hydropower_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydropower',
            name='date_of_operation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hydropower',
            name='capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hydropower',
            name='lic_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hydropower',
            name='license_type',
            field=models.CharField(max_length=100),
        ),
    ]
