# Generated by Django 2.0.8 on 2018-08-09 10:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180809_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydropower',
            name='latlong',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
