# Generated by Django 2.0.8 on 2018-08-15 00:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hydropower_latlong'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydropower',
            name='other_properties',
            field=jsonfield.fields.JSONField(default='SOME STRING', max_length=140),
        ),
    ]
