# Generated by Django 2.0.8 on 2018-08-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180820_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydropower',
            name='date_of_operation',
            field=models.CharField(max_length=100),
        ),
    ]
