# Generated by Django 2.0.8 on 2018-08-15 04:12

import django.contrib.gis.db.models.fields
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hydropower_other_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydropower',
            name='latlong',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='hydropower',
            name='other_properties',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
