# Generated by Django 2.0.8 on 2018-08-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180815_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydropower',
            name='proj_size',
            field=models.CharField(max_length=100),
        ),
    ]
