# Generated by Django 2.0.8 on 2018-09-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gislayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydropower',
            name='issue1_date',
        ),
        migrations.RemoveField(
            model_name='hydropower',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hydropower',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='hydropower',
            name='validity1_date',
        ),
    ]
