# Generated by Django 2.0.8 on 2018-08-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180816_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydropower',
            name='trans_cate',
            field=models.CharField(max_length=100),
        ),
    ]
