# Generated by Django 2.0.8 on 2018-09-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180920_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='gislayer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
