# Generated by Django 2.0.8 on 2018-09-27 08:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_gislayer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydropower',
            name='hydro_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gislayer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='geojsons/', validators=[core.models.validate_file_extension]),
        ),
    ]
