# Generated by Django 2.0.8 on 2018-09-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180927_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='hydro_summary',
        ),
        migrations.AddField(
            model_name='hydropower',
            name='hydro_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
