# Generated by Django 2.0.8 on 2018-10-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180928_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydropower',
            name='capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacity (MW)'),
        ),
    ]
