# Generated by Django 2.0.8 on 2018-10-31 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181026_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opacity', models.IntegerField(default=0, null=True)),
                ('fill_opacity', models.IntegerField(default=0, null=True, verbose_name='Fill Opacity')),
                ('weight', models.IntegerField(default=0, null=True)),
                ('dash_array', models.IntegerField(default=0, null=True, verbose_name='Dash Array')),
                ('dash_offset', models.IntegerField(default=0, null=True, verbose_name='Dash Offset')),
                ('color', models.CharField(max_length=200)),
                ('fill_color', models.CharField(max_length=200, verbose_name='Fill Color')),
                ('gislayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gisstyle', to='core.Gislayer')),
            ],
        ),
    ]
