# Generated by Django 2.0.8 on 2018-11-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_gisstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisstyle',
            name='color',
            field=models.CharField(default='#ffffff', max_length=200),
        ),
        migrations.AlterField(
            model_name='gisstyle',
            name='fill_color',
            field=models.CharField(default='#ffffff', max_length=200, verbose_name='Fill Color'),
        ),
        migrations.AlterField(
            model_name='gisstyle',
            name='fill_opacity',
            field=models.IntegerField(default=0.2, null=True, verbose_name='Fill Opacity'),
        ),
        migrations.AlterField(
            model_name='gisstyle',
            name='opacity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gisstyle',
            name='weight',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
