# Generated by Django 2.0.8 on 2018-11-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181101_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisstyle',
            name='color',
            field=models.CharField(default='#000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='gisstyle',
            name='fill_color',
            field=models.CharField(default='#000000', max_length=200, verbose_name='Fill Color'),
        ),
        migrations.AlterField(
            model_name='gisstyle',
            name='fill_opacity',
            field=models.FloatField(default=0.2, null=True, verbose_name='Fill Opacity'),
        ),
    ]
