# Generated by Django 2.0.8 on 2018-11-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181102_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisstyle',
            name='gislayer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gisstyle', to='core.Gislayer'),
        ),
    ]
